ball_balancer:
 # Publish joint states
 joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
 
 # Position controller
 seesaw_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: seesaw_joint
  pid: {p: 100.0, i: 100, d: 20.0}
 
